language: python
python:
  - "3.4"

#Django & Database
addons:
  postgresql: "9.4"

env:
  -DJANGO=1.9.5 DB=postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - python manage.py test
  - coverage run --source=iam_manager manage.py test

after_success:
  coveralls